name: Provision with Terraform
run-name: Provision with Terraform

on:
  workflow_dispatch:
    inputs:
      hubEnv:
        description: Select target hub and stage
        required: true
        type: choice
        options:
          - 'BACKEND_EMEA_TEST'


jobs:
  properties:
    uses: ./.github/workflows/datacenterMap.yml
    with:
      hubEnv: ${{ inputs.hubEnv }}
    secrets: inherit

  terraform:
    runs-on: ubuntu-latest
    needs: properties
    env:
      AWS_ACCOUNT: ${{ needs.properties.outputs.AWS_ACCOUNT }}
      AWS_KEY:  ${{ secrets.BACKEND_EMEA_TEST_AWS_KEY }}
      AWS_SECRET: ${{ secrets.BACKEND_EMEA_TEST_AWS_SECRET }}
      REGION: ${{ needs.properties.outputs.REGION }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0

      - name: Install Terraform ${{ env.terraform_version }}
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.terraform_version }}
          terraform_wrapper: false
        env:
          terraform_version: 1.5.7

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ env.AWS_KEY }}
          aws-secret-access-key: ${{ env.AWS_SECRET }}
          aws-region: ${{ env.REGION }}

      - name: Run Terraform apply
        run: |
          cd aws-infrastructure/terraform
          chmod +x setup_new_region.sh
          chmod +x w2.sh
          ./setup_new_region.sh w2.sh backend-test eu-central-1 emea plan
